### ISSUE TITLE
error in sample code for Metalama 'Log Attribute

### ISSUE THREAD

**Issue by billwoo** [postsharp/Metalama#7]
https://try.metalama.net/

The sample code has the line:

return result;
Console.WriteLine( meta.Target.Method.ToDisplayString() + " failed: " + e.Message );

inside the 'Try clause: it should be moved to the 'Catch clause:

catch (Exception e)
        {
            Debug.WriteLine(meta.Target.Method.ToDisplayString() + " failed: " + e.Message);
            throw;
        }

**Comment by gfraiteur** [comment]
Hi @billwoo , sorry for late answer, we had an issue with processing the notifications.

I don't understand your bug report. In which example is it. Could you click on the _Share_ button of the example and paste it here?

Thanks.

Doing `Debug.WriteLine` in a sample would probably not work because the namespace/class would be forbidden.
